Safeher/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from women.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('signup/', signup1, name='signup'),
    path('login/', userlogin, name='login'),
    path('logout/', Logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('changepassword/', changepassword, name='changepassword'),
    path('menstrual/', menstrual, name='menstrual'),
    path('bmi/', bmi, name='bmi'),
    path('browse/', browse, name='browse'),
    path('helpline/', helpline, name='helpline'),
    path('information/', information, name='information'),
    path('upload_queries/', upload_queries, name='upload_queries'),
    path('faq/', faq, name='faq'),
    path('vaccine/', vaccine, name='vaccine'),
    path('magazine/', magazine, name='magazine'),
    path('ngos/', ngos, name='ngos'),
    path('login_admin/', login_admin, name='login_admin'),
    path('admin_home/', admin_home, name='admin_home'),
    path('pending_queries/', pending_queries, name='pending_queries'),
    path('accepted_queries/', accepted_queries, name='accepted_queries'),
    path('rejected_queries/', rejected_queries, name='rejected_queries'),
    path('all_queries/', all_queries, name='all_queries'),
    path('assign_status/<int:pid>', assign_status, name='assign_status'),
    path('pending_m/', pending_m, name='pending_m'),
    path('accepted_m/', accepted_m, name='accepted_m'),
    path('rejected_m/', rejected_m, name='rejected_m'),
    path('all_m/', all_m, name='all_m'),
    path('assignstatus_m/<int:pid>', assignstatus_m, name='assignstatus_m'),
    path('upload_m/', upload_m, name='upload_m'),
    path('view_m/', view_m, name='view_m'),
    path('view_users/', view_users, name='view_users'),
    path('delete_user/<int:pid>', delete_user, name='delete_user'),
    path('delete_notes/<int:pid>', delete_notes, name='delete_notes'),
    path('delete_m/<int:pid>', delete_m, name='delete_m'),
    path('chat/', include('chat.urls')),
    #password reset
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.contrib.auth import logout
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('register/', views.register_view, name='register'),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import TextInput


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields=['username','password1','password2']
        widgets = {
            'username': TextInput(attrs={'class':'form-control'}),
        }

chat/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from chat.models import Message
from chat.forms import SignUpForm


def index(request):
    if request.user.is_authenticated:
        return redirect('chats')
    if request.method == 'GET':
        return render(request, 'chat/index.html', {})
    if request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            return HttpResponse('{"error": "User does not exist"}')
        return redirect('chats')


def register_view(request):
    """
    Render registration template
    """
    if request.method == 'POST':
        print("working1")
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('chats')
    else:
        print("working2")
        form = SignUpForm()
    template = 'chat/register.html'
    context = {'form':form}
    return render(request, template, context)


def chat_view(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, 'chat/chat.html',
                      {'users': User.objects.exclude(username=request.user.username)})


def message_view(request, sender, receiver):
    if not request.user.is_authenticated:
        return redirect('index')
    else:
        return render(request, "chat/messages.html",
                      {'users': User.objects.exclude(username=request.user.username),
                       'receiver': User.objects.get(id=receiver),
                       'messages': Message.objects.filter(sender_id=sender, receiver_id=receiver) |
                                   Message.objects.filter(sender_id=receiver, receiver_id=sender)})

chat/templates/chat/chat.html
{% extends 'chat/index.html' %}
{% load static %}
{% block body %}
<nav class="blue lighten-3">
    <div class="nav-wrapper container">
      <a href="{% static 'chat.png' %}" class="brand-logo">Chat</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="">{{ request.user.username }}</a></li>
      </ul>
    </div>
</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
        <div class="card">
            <div class="collection">
                {% for user in users %}
                <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                    <img src="{% static 'chat.png' %}" style="width: 16%;" class="col s4">
                    <div class="col s8">
                    <span class="title" style="font-weight: bolder">{{ user.username }}</span>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        </div>
        <div class="col s9">
            <div class="card">
            <div id="board" class="messages" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="msg_field" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button name="send" class="btn btn-floating blue lighten-2 waves-effect waves-light" id="send_btn"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load static %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        // //For sending
        // $(function () {
        //     scrolltoend();
        //     $('#chat-box').on('submit', function (event) {
        //         event.preventDefault();
        //         var message = $('#id_message');
        //         send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
        //         message.val('');
        //     })
        // })



        var messageBody = document.querySelector('.messages');
        messageBody.scrollTop = messageBody.scrollHeight - messageBody.clientHeight;

        function scrolltoend() {
            $('#board').stop().animate({
                scrollTop: $('#board')[0].scrollHeight
            }, 800);
         }

        const text_box = '<div class="container darker">' +
            '<img src="#" alt="Avatar" class="right" style="width:100%;">' +
            '<p>{description}</p>' +
            '<span class="time-right">{time}</span>' +
            '</div>'

        //For sending
        $(function () {
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#msg_field');
                send('{{ curr_user.username }}', '{{ friend.username }}', message.val());
                message.val('');
            })
        })

        function send(sender, receiver, message){

            $.post('/api/messages', '{"sender_name": "' + sender + '", "receiver_name": "' +
                    receiver + '","description": "' + message + '" }', function (data) {
                var field = text_box.replace('{description}', message);
                var today = new Date();
                var time = today.getHours() + ":" + today.getMinutes()
                field = field.replace('{time}', time)
                $('#board').append(field);
                scrolltoend();
            })
        }
    </script>
{% endblock %}

chat/templates/chat/index.html
{% load static %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>

    <body>
    {% block body %}
        <div class="section blue lighten-3">
            <div class="container white-text center-align text">
            <h2>A special Chat for Youuuu</h2>
            <p>A Chatting App.</p>
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3>
                    Login
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}">Register</a>
                            </div>
                            <div class="col s4">
                            <div class="right">
                                <button class="btn blue waves-effect waves-light pull-s12">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>

  </html>

chat/templates/chat/messages.html
{% extends 'chat/chat.html' %}
<!-- {% block hide %}{% endblock %} -->
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})

function scrolltoend() {
    $('#board').stop().animate({
        scrollTop: $('#board')[0].scrollHeight
    }, 800);
}

$(function () {
    setInterval(receive, 1000)
})

const text = '<div class="container">'
            + '<img src="#" alt="Avatar" style="width:100%;">' +
            '<p>{description}</p>' +
            '<span class="time-left">{time}</span>' +
            '</div>'

function receive(){
    $.get('/api/messages/' + sender_id + '/' + receiver_id, function(data){
        if(data.length !== 0){
            for(var i = 0; i < data.length; i++){
                var field = text.replace('{description}', data[i].description);
                var time = data[i].time.slice(0, 5) + ' a.m'
                field = field.replace('{time}', time);
                $('#board').append(field);
                scrolltoend();
            }
        }
    })
}
</script>
{% endblock %}

chat/templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3>
    Register
    </h3>
    <form id="register-form" class="form-group" method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    {{ form.username }}
                    <label for="id_username" data-error="Username already taken">Email</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password1 }}
                    <label for="id_password">Password</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password2 }}
                    <label for="id_password2">Repeat Password</label>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                <div class="right">
                    <button class="btn blue waves-effect waves-light pull-s12">Register</button>
                </div>
                </div>
            </div>
    </form>
{% endblock %}